URL_SERVICE = "https://c2a41abf-c9e7-489f-95bb-814e6355f46d.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
# LOG_MAIN_PATH = "/api/logs/main/"
# USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
# USERS_KITS_PATH = "/api/v1/kits"
# CREATE_USER_PATH = "/api/v1/users/"
# PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
# CREATE_KITS_PATH = "/api/v1/kits/"
CREATE_ORDER_PATH = "/api/v1/orders/"
GET_ORDER_VIA_TRACK = "/v1/orders/track?t="
